"""3D Analysis public API.

This namespace contains same-sample, multi-slice Xenium contour workflows.
It includes conservative TPS soft alignment for a hard-aligned contour pair
and pyXenium-backed multi-slice contour stack reconstruction.
"""

from __future__ import annotations

from .soft_alignment import (
    ThreeDContourReconstructionConfig,
    ThreeDContourReconstructionResult,
    ThreeDFeatureUnavailableError,
    run_3d_contour_reconstruction,
)
from .image_registration import (
    CODA_METHOD_CREDIT,
    CODA_METHOD_REFERENCE_DOI,
    CODA_METHOD_REFERENCE_URL,
    CODA_METHODOLOGY_URL,
    CodaImageRegistrationConfig,
    CodaImageRegistrationResult,
    RadonRotationResult,
    TranslationResult,
    apply_similarity_to_points,
    estimate_coda_image_registration,
    estimate_radon_rotation,
    estimate_translation,
)
from .multislice import (
    ThreeDStackReconstructionConfig,
    ThreeDStackReconstructionResult,
    discover_xenium_slices,
    hard_align_geojson,
    reconstruct_3d_contour_meshes,
    run_3d_stack_reconstruction,
    write_3d_contour_points,
    write_3d_visualization_html,
)
from .cell_cloud import (
    CELL_CLOUD_ALIGNED_XY_OBSM_KEY,
    CELL_CLOUD_OBS_SLICE_KEY,
    CELL_CLOUD_OBSM_KEY,
    CELL_CLOUD_UNS_KEY,
    CellCloudProjectionConfig,
    CellCloudProjectionResult,
    CellCloudRenderConfig,
    CellCloudRenderResult,
    build_alignment_manifest,
    cell_cloud_cache_status,
    cell_cloud_dataframe_from_coordinates,
    hash_alignment_manifest,
    load_cell_alignment_transforms,
    project_cell_coordinates,
    render_cell_cloud_html,
    run_cell_cloud_projection,
    write_cell_cloud_cache,
)
from .gland_qc import (
    GlandQCAtlasConfig,
    GlandQCAtlasResult,
    render_gland_qc_atlas,
)
from .gland_instances import (
    DEFAULT_EPITHELIAL_MARKERS,
    DEFAULT_EPITHELIAL_STRUCTURES,
    GlandInstanceSegmentationConfig,
    GlandInstanceSegmentationResult,
    segment_gland_instances,
)
from .gland_tracking import (
    GlandInstanceTrackingConfig,
    GlandInstanceTrackingResult,
    track_gland_instances,
)
from .gland_atlas import (
    GlandInstanceAtlasResult,
    GlandInstanceDetectionResult,
    render_gland_instance_atlas,
    run_gland_instance_detection,
)
from .spatial_modules import (
    GeneStructureQuantificationConfig,
    GeneStructureQuantificationResult,
    SpatialModuleDiscoveryConfig,
    SpatialModuleDiscoveryResult,
    SpatialModulePlotConfig,
    SpatialModulePlotResult,
    compute_hotspot_overlap_metrics,
    compute_hotspot_sdf_metrics,
    plot_spatial_module_clustermap,
    quantify_gene_structure_relationships,
    run_spatial_module_discovery,
)

__all__ = [
    "CELL_CLOUD_ALIGNED_XY_OBSM_KEY",
    "CELL_CLOUD_OBS_SLICE_KEY",
    "CELL_CLOUD_OBSM_KEY",
    "CELL_CLOUD_UNS_KEY",
    "CODA_METHOD_CREDIT",
    "CODA_METHOD_REFERENCE_DOI",
    "CODA_METHOD_REFERENCE_URL",
    "CODA_METHODOLOGY_URL",
    "CellCloudProjectionConfig",
    "CellCloudProjectionResult",
    "CellCloudRenderConfig",
    "CellCloudRenderResult",
    "CodaImageRegistrationConfig",
    "CodaImageRegistrationResult",
    "DEFAULT_EPITHELIAL_MARKERS",
    "DEFAULT_EPITHELIAL_STRUCTURES",
    "GeneStructureQuantificationConfig",
    "GeneStructureQuantificationResult",
    "GlandInstanceAtlasResult",
    "GlandInstanceDetectionResult",
    "GlandInstanceSegmentationConfig",
    "GlandInstanceSegmentationResult",
    "GlandInstanceTrackingConfig",
    "GlandInstanceTrackingResult",
    "GlandQCAtlasConfig",
    "GlandQCAtlasResult",
    "RadonRotationResult",
    "SpatialModuleDiscoveryConfig",
    "SpatialModuleDiscoveryResult",
    "SpatialModulePlotConfig",
    "SpatialModulePlotResult",
    "ThreeDContourReconstructionConfig",
    "ThreeDContourReconstructionResult",
    "ThreeDFeatureUnavailableError",
    "ThreeDStackReconstructionConfig",
    "ThreeDStackReconstructionResult",
    "TranslationResult",
    "apply_similarity_to_points",
    "compute_hotspot_overlap_metrics",
    "compute_hotspot_sdf_metrics",
    "build_alignment_manifest",
    "cell_cloud_cache_status",
    "cell_cloud_dataframe_from_coordinates",
    "discover_xenium_slices",
    "estimate_coda_image_registration",
    "estimate_radon_rotation",
    "estimate_translation",
    "hard_align_geojson",
    "hash_alignment_manifest",
    "load_cell_alignment_transforms",
    "plot_spatial_module_clustermap",
    "project_cell_coordinates",
    "quantify_gene_structure_relationships",
    "reconstruct_3d_contour_meshes",
    "render_cell_cloud_html",
    "render_gland_instance_atlas",
    "render_gland_qc_atlas",
    "run_3d_contour_reconstruction",
    "run_cell_cloud_projection",
    "run_gland_instance_detection",
    "run_spatial_module_discovery",
    "run_3d_stack_reconstruction",
    "segment_gland_instances",
    "track_gland_instances",
    "write_3d_contour_points",
    "write_3d_visualization_html",
    "write_cell_cloud_cache",
]
